#!/usr/bin/env python3
"""Build index.html (the installable home-screen app) from qnt-dashboard.html.

qnt-dashboard.html is the single source. It is written for the claude.ai
artifact viewer, which supplies its own <!doctype>/<head>/<body>. This wraps
it in a full document and adds the app manifest, icons and status-bar tags.

Run after editing qnt-dashboard.html:  python3 build.py
"""
from pathlib import Path

root = Path(__file__).parent
src = (root / "qnt-dashboard.html").read_text(encoding="utf-8")

marker = '<div class="wrap">'
cut = src.index(marker)
head_part, body_part = src[:cut].strip(), src[cut:].strip()

app_head = """<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="description" content="Live Quant (QNT) price, chart, order book, trades and news.">
<meta name="theme-color" content="#EEF1F6" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0A0E16" media="(prefers-color-scheme: dark)">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="QNT">
<link rel="manifest" href="manifest.webmanifest">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="icons/favicon-32.png">
<link rel="icon" type="image/svg+xml" href="icons/icon.svg">
<style>:root{padding-top:env(safe-area-inset-top,0px);padding-bottom:env(safe-area-inset-bottom,0px);padding-left:env(safe-area-inset-left,0px);padding-right:env(safe-area-inset-right,0px)}body{margin:0}img{max-width:100%}[hidden]{display:none!important}</style>"""

out = (
    "<!doctype html>\n<html lang=\"en\">\n<head>\n"
    "<!-- Generated by build.py from qnt-dashboard.html. Do not edit by hand. -->\n"
    + app_head + "\n" + head_part + "\n</head>\n<body>\n" + body_part + "\n</body>\n</html>\n"
)
(root / "index.html").write_text(out, encoding="utf-8")
print("wrote index.html", len(out), "bytes")
